<?php
/**
 * Holds all the functionality needed
 * to register the plugin's ACF fields.
 *
 * @package WPCampus Speakers
 */

/**
 * Register the plugin's ACF fields.
 */
function wpcampus_speakers_add_fields() {
	if ( function_exists( 'acf_add_local_field_group' ) ) :

		acf_add_local_field_group( array(
			'key' => 'group_5a34bf1b846ab',
			'title' => __( 'Proposal: The Event', 'wpcampus-speakers' ),
			'fields' => array(
				array(
					'key' => 'field_5a35c6908042b',
					'label' => __( 'Event', 'wpcampus-speakers' ),
					'name' => 'proposal_event',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'taxonomy' => 'proposal_event',
					'field_type' => 'select',
					'allow_null' => 1,
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'multiple' => 0,
				),
				array (
					'key' => 'field_5aadc66499ff1',
					'label' => __( 'Best Session', 'wpcampus-speakers' ),
					'name' => 'best_session',
					'type' => 'radio',
					'instructions' => __( 'Was this session selected as "Best Speaker" or "Best Session" of the event?', 'wpcampus-speakers' ),
					'required' => 0,
					'conditional_logic' => 0,
					'choices' => array (
						1 => 'Yes',
						0 => 'No',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 0,
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5a34bf2121f2d',
					'label' => __( 'Proposal Status', 'wpcampus-speakers' ),
					'name' => 'proposal_status',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'choices' => array(
						'confirmed' => __( 'Confirmed', 'wpcampus-speakers' ),
						'declined' => __( 'Declined', 'wpcampus-speakers' ),
						'selected' => __( 'Selected', 'wpcampus-speakers' ),
						'submitted' => __( 'Submitted', 'wpcampus-speakers' ),
					),
					'allow_null' => 1,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'submitted',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'proposal',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

		acf_add_local_field_group( array(
			'key' => 'group_5a34bc2ca0126',
			'title' => __( 'Proposal: The Speaker(s)', 'wpcampus-speakers' ),
			'fields' => array(
				array(
					'key' => 'field_5a361d609530c',
					'label' => __( 'Speakers', 'wpcampus-speakers' ),
					'name' => 'speakers',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'collapsed' => 'field_5a361daa9530d',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => __( 'Add Speaker', 'wpcampus-speakers' ),
					'sub_fields' => array(
						array(
							'key' => 'field_5a361daa9530d',
							'label' => __( 'Speaker', 'wpcampus-speakers' ),
							'name' => 'speaker',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'post_type' => array(
								0 => 'profile',
							),
							'allow_null' => 1,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'proposal',
					),
				),
			),
			'menu_order' => 3,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

		acf_add_local_field_group(array(
			'key' => 'group_5a80b2ac9a829',
			'title' => __( 'Proposal: The Asset(s)', 'wpcampus-speakers' ),
			'fields' => array(
				array(
					'key' => 'field_5a80b2cb6635e',
					'label' => __( 'Session Video', 'wpcampus-speakers' ),
					'name' => 'session_video',
					'type' => 'post_object',
					'instructions' => __( 'Select the recording from our library of videos.', 'wpcampus-speakers' ),
					'required' => 0,
					'conditional_logic' => 0,
					'post_type' => array(
						0 => 'video',
					),
					'allow_null' => 1,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'proposal',
					),
				),
			),
			'menu_order' => 5,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'field',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));
	endif;

	acf_add_local_field_group( array(
		'key' => 'group_5a34bdaa05360',
		'title' => __( 'Profile: Speaker', 'wpcampus-speakers' ),
		'fields' => array(
			array(
				'key' => 'field_5a34b9ebae921',
				'label' => __( 'First Name', 'wpcampus-speakers' ),
				'name' => 'first_name',
				'type' => 'text',
				'instructions' => __( 'The first name field is used solely for sorting purposes. The name in the "Display Name" field will be used for display.', 'wpcampus-speakers' ),
				'required' => 1,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'First name', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a34ba00ae922',
				'label' => __( 'Last Name', 'wpcampus-speakers' ),
				'name' => 'last_name',
				'type' => 'text',
				'instructions' => __( 'The last name field is used solely for sorting purposes. The name in the "Display Name" field will be used for display.', 'wpcampus-speakers' ),
				'required' => 1,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Last name', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a34bcb2c5dbe',
				'label' => __( 'Display Name', 'wpcampus-speakers' ),
				'name' => 'display_name',
				'type' => 'text',
				'instructions' => __( 'How would you like your name displayed? This allows us to use the post title field for administrative purposes.', 'wpcampus-speakers' ),
				'required' => 1,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'How would you like your name displayed?', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'profile',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group( array(
		'key' => 'group_5a34b4cd1252a',
		'title' => __( 'Profile: Contact Information (Private)', 'wpcampus-speakers' ),
		'fields' => array(
			array(
				'key' => 'field_5a34b4e57b7d7',
				'label' => sprintf( __( '%s User', 'wpcampus-speakers' ), 'WordPress' ),
				'name' => 'wordpress_user',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'role' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array(
				'key' => 'field_5a34b5af7b7d8',
				'label' => __( 'Email Address', 'wpcampus-speakers' ),
				'name' => 'email',
				'type' => 'email',
				'instructions' => __( 'Please provide an email address that may be used to contact the speaker.', 'wpcampus-speakers' ) . '<br /><em>' . __( 'This information will only be used for administrative purposes and will not be displayed on the front-end of the website.', 'wpcampus-speakers' ) . '</em>',
				'required' => 1,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Email address', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a34b5e57b7d9',
				'label' => __( 'Phone Number', 'wpcampus-speakers' ),
				'name' => 'phone',
				'type' => 'text',
				'instructions' => __( 'Please provide a phone number that may be used to contact the speaker.', 'wpcampus-speakers' ) . '<br /><em>' . __( 'This information will only be used for administrative purposes and will not be displayed on the front-end of the website.', 'wpcampus-speakers' ) . '</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Phone number', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'profile',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group( array(
		'key' => 'group_5a34be3ed37e2',
		'title' => __( 'Profile: Contact Information (Public)', 'wpcampus-speakers' ),
		'fields' => array(
			array(
				'key' => 'field_5a34b8d0a45ad',
				'label' => __( 'Personal Website', 'wpcampus-speakers' ),
				'name' => 'website',
				'type' => 'url',
				'instructions' => __( "Please provide the URL for the speaker's personal website.", 'wpcampus-speakers' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Personal website', 'wpcampus-speakers' ),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'profile',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group( array(
		'key' => 'group_5a34b89e23894',
		'title' => __( 'Profile: Professional Information (Public)', 'wpcampus-speakers' ),
		'fields' => array(
			array(
				'key' => 'field_5a34b8e8a45ae',
				'label' => __( 'Company', 'wpcampus-speakers' ),
				'name' => 'company',
				'type' => 'text',
				'instructions' => __( 'Where does the speaker work?', 'wpcampus-speakers' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Where does the speaker work?', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a34b906a45af',
				'label' => __( 'Company Website', 'wpcampus-speakers' ),
				'name' => 'company_website',
				'type' => 'url',
				'instructions' => __( "Please provide the URL for the speaker's company website.", 'wpcampus-speakers' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Company website', 'wpcampus-speakers' ),
			),
			array(
				'key' => 'field_5a34b91aa45b0',
				'label' => __( 'Company Position', 'wpcampus-speakers' ),
				'name' => 'company_position',
				'type' => 'text',
				'instructions' => __( "Please provide the speaker's job title.", 'wpcampus-speakers' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => __( 'Job title', 'wpcampus-speakers' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'profile',
				),
			),
		),
		'menu_order' => 8,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group( array(
		'key' => 'group_5a34b72214e1b',
		'title' => __( 'Profile: Social Media (Public)', 'wpcampus-speakers' ),
		'fields' => array(
			array(
				'key' => 'field_5a34b78e600c5',
				'label' => sprintf( __( '%s URL', 'wpcampus-speakers' ), 'Facebook' ),
				'name' => 'facebook',
				'type' => 'url',
				'instructions' => sprintf( __( 'Please provide the full %s URL.', 'wpcampus-speakers' ), 'Facebook' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => sprintf( __( '%s URL', 'wpcampus-speakers' ), 'Facebook' ),
			),
			array(
				'key' => 'field_5a34b7a2600c6',
				'label' => sprintf( __( '%s Username', 'wpcampus-speakers' ), 'Instagram' ),
				'name' => 'instagram',
				'type' => 'text',
				'instructions' => sprintf( __( 'Only provide the %s handle or username.', 'wpcampus-speakers' ), 'Instagram' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => sprintf( __( '%s handle or username', 'wpcampus-speakers' ), 'Instagram' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a34b7c7c416b',
				'label' => sprintf( __( '%s Username', 'wpcampus-speakers' ), 'Twitter' ),
				'name' => 'twitter',
				'type' => 'text',
				'instructions' => sprintf( __( 'Only provide the %1$s handle, without the "%2$s".', 'wpcampus-speakers' ), 'Twitter', '@' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => sprintf( __( '%1$s handle without the "%2$s"', 'wpcampus-speakers' ), 'Twitter', '@' ),
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a34b7e1c416c',
				'label' => sprintf( __( '%s URL', 'wpcampus-speakers' ), 'LinkedIn' ),
				'name' => 'linkedin',
				'type' => 'url',
				'instructions' => sprintf( __( 'Please provide the full %s URL.', 'wpcampus-speakers' ), 'LinkedIn' ),
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => sprintf( __( '%s URL', 'wpcampus-speakers' ), 'LinkedIn' ),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'profile',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
}
add_action( 'plugins_loaded', 'wpcampus_speakers_add_fields' );
